add eject shooter command
FRCTeam3255/2024_Sportbot_Code pull request #76
Opened 2024-11-17 05:04 UTC by Wu-Fan-529

2024-11-19 15:12 UTC, TaylerUva requested changes

2024-11-19 15:12 UTC, TaylerUva commented on src/main/java/frc/robot/commands/EjectShooter.java
> +    globalStager.setTopStagerMotorVelocity(Constants.constStager.TOP_STAGER_MOTOR_VELOCITY);
Does anything else need to happen here? What does the stager push into?

2024-11-19 15:26 UTC, Wu-Fan-529 commented on src/main/java/frc/robot/commands/EjectShooter.java
> +    globalStager.setTopStagerMotorVelocity(Constants.constStager.TOP_STAGER_MOTOR_VELOCITY);
It will push the ball into the shooter, like the shoot command, but do not  need speed requirements for the shooter motors.

2024-11-23 00:56 UTC, TaylerUva requested changes

2024-11-23 00:56 UTC, TaylerUva commented on src/main/java/frc/robot/commands/EjectShooter.java
> +    globalStager.setTopStagerMotorVelocity(Constants.constStager.TOP_STAGER_MOTOR_VELOCITY);
We probably want to "shoot" it out as well so we don't have to click another button to eject

2024-11-23 03:51 UTC, TaylerUva approved these changes

2024-11-23 03:51 UTC, merged