made LEDs for the shoot command🦟™️
FRCTeam3255/2024_Sportbot_Code pull request #77
Opened 2024-11-23 19:36 UTC by BrodyKarr

2024-11-23 19:40 UTC, TaylerUva requested changes

2024-11-23 19:40 UTC, TaylerUva commented on src/main/java/frc/robot/Constants.java
> +<<<<<<< Updated upstream
Delete

2024-11-23 19:40 UTC, TaylerUva commented on src/main/java/frc/robot/Constants.java
> +
Delete

2024-11-23 19:40 UTC, TaylerUva commented on src/main/java/frc/robot/Constants.java
> +>>>>>>> Stashed changes
Delete

2024-11-23 23:18 UTC, TaylerUva requested changes
Overall very good just a few issues

2024-11-23 23:18 UTC, TaylerUva commented on src/main/java/frc/robot/RobotContainer.java
> +    m_driverController.btn_RightBumper.whileTrue(com_EjectShooter);
You altered the button mappings from what they should be

2024-11-23 23:18 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Drive.java
> +    globalLED.setLEDs(constLED.LED_DRIVE);
Drive is always running so it should not have any LEDs

2024-11-23 23:18 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Shoot.java
> +      }
You undid the constants with the merge conflict resolution

2024-12-07 17:54 UTC, BrodyKarr commented on src/main/java/frc/robot/commands/intakeHopper.java
> +    subHopper.setOrientationMotorSpeed(.5);
delete line 32

2024-12-07 17:55 UTC, BrodyKarr commented on src/main/java/frc/robot/commands/EjectGP.java
> +    globalIntake.setIntakeVelocity(-0.5);
replace this line with globalIntake.setIntakeVelocity(Constants.constIntake.INTAKE_EJECT_VELOCITY)

2024-12-07 18:29 UTC, TaylerUva approved these changes

2024-12-07 18:29 UTC, merged